services:
  - type: web
    name: cafe-website-3d-and-animation-
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18